default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kkkkk
  password: test12345

development:
  <<: *default
  database: tn_qna_development

test:
  <<: *default
  database: tn_qna_test